#deploy
steps:
- name: gcr.io/cloud-builders/gsutil
  id: Deploy
  args: ['-m', 'rsync', '-r', './dags', 'gs://${_COMPOSER_BUCKET}/dags']
substitutions:
    _COMPOSER_BUCKET: us-central1-sample-composer-10f74102-bucket